### ISSUE TITLE
Settings menu

### ISSUE THREAD

**Issue by marcusbirkeland** [JoakimAustvold/WordleBattle#15]
Make settings menu accessible from top-right of the screen. On click, open the menu.

Should include:

- Exit game button (opens main menu)
- Volume slider
- Show rules button

Settings should be saved on the device, and loaded automatically on app start. Use localstorage or euqivalent to store

**Comment by karenvi** [comment]
@JoakimAustvold ser ut som du har kommet et stykke på denne i main menu branchen, vil du gjøre denne oppgaven alene?

**Comment by JoakimAustvold** [comment]
Added the settings-screen branch to development. This branch should be updated to main and with the changes to the main menu screen.
