### ISSUE TITLE
Tutorial Dialog

### ISSUE THREAD

**Issue by marcusbirkeland** [JoakimAustvold/WordleBattle#19]
Make a tutorial menu that opens upon starting the first game.

Acceptance criteria:

- Store a boolean variable in device LocalStorage:  hasPlayed = false.
- Upon starting a new game, check hasPlayed
- if false, start the tutorial dialog
- The dialog should show info on how to play, optionally contain images or multiple slides.
- When tutorial is over, set hasPlayed = true

**Comment by JoakimAustvold** [comment]
Added the tutorial-screen branch to development. This branch should be updated to main and with the changes to the main menu screen.

**Comment by millieba** [comment]
@JoakimAustvold, jobber du på denne nå? Karen og jeg er assigned denne issuen
