### ISSUE TITLE
Wordle Duel - multiplayer gamemode

### ISSUE THREAD

**Issue by marcusbirkeland** [JoakimAustvold/WordleBattle#21]
- [x] Add view and controller for inputting a word that the other player should guess.  Word should be validated.
- [x] Add functionality for sending and recieveing the word to firebase session. A game should start for your opponent whenever they recieve the word, and vice versa.
- [x] Check what happens if a player can't solve the wordle
- [x] Return to different pages on "Leave lobby" (and also call it back to lobby instead)
- [x] Fix an alternative to option menu

**Comment by Thomaszzs** [comment]
Skal se på å lage views for multiplayer, og view for input av ordene
