### ISSUE TITLE
Generate random words

### ISSUE THREAD

**Issue by karenvi** [JoakimAustvold/WordleBattle#3]
Get random words with length 5 from an API or something, which the user(s) must guess:
* Find appropriate source of words 
* Implement it into the code, make sure developers can fetch the words for later use

**Comment by Thomaszzs** [comment]
Yes, there are several dictionary APIs that you can use for an Android project. Here are a few options:

1. Merriam-Webster Dictionary API - This API provides access to the Merriam-Webster Dictionary and Thesaurus, including definitions, pronunciations, example sentences, and synonyms. You can sign up for a free API key at https://dictionaryapi.com/.

2. Oxford Dictionaries API - This API provides access to the Oxford English Dictionary, including definitions, pronunciations, example sentences, and more. You can sign up for a free API key at https://developer.oxforddictionaries.com/.

3. Wordnik API - This API provides access to a variety of dictionaries, including definitions, example sentences, related words, and more. You can sign up for a free API key at https://developer.wordnik.com/.

4. ~~Urban Dictionary API - This API provides access to the Urban Dictionary, a crowdsourced dictionary of slang words and phrases. You can access the API without an API key at https://api.urbandictionary.com/v0/.~~

5. Google Dictionary API - This API provides access to Google's online dictionary, including definitions, synonyms, and translations. You can access the API without an API key at https://dictionaryapi.dev/.

Note that some of these APIs may have usage limits or require payment for higher usage volumes. You should carefully review the terms of service and pricing options before selecting an API to use in your Android project.

**Comment by JoakimAustvold** [comment]
Norsk ordbok api fra UIB:
https://ordbokene.no/api
