### ISSUE TITLE
Update UI 

### ISSUE THREAD

**Issue by cldahl** [JoakimAustvold/WordleBattle#43]
Fonts and buttons don't match, so the text overflows in certain locations.
Also need to make tutorial readable.

**Comment by marcusbirkeland** [comment]
> Fonts and buttons don't match, so the text overflows in certain locations. Also need to make tutorial readable.

Dette kommer av at de fleste knappene bruker table-layout, som oppfører seg uavhengig av styling på andre knapper og sånn. Når jeg setter font-size i View-klassen virker det også bare til å påvirker knapper :: 🤔
