### ISSUE TITLE
Wordgrid

### ISSUE THREAD

**Issue by marcusbirkeland** [JoakimAustvold/WordleBattle#5]
## Word grid for the game

Acceptance criteria:
- Display a word grid containing cells for each letter in a 5-letter word.  Should have 6 rows for words.
- Word grid should be wired to the keyboard input. Whenever a valid 5-letter word is input, it should display the letters on the current row in the grid.
- When a word is input, each cell should get colored accordingly. Yellow background for letters that are in the word, but not correct position. Green backround for letters that are placed on the correct position of the word.
![image](https://user-images.githubusercontent.com/36818485/224702409-296e1e70-e269-478d-8975-13af8604f4a3.png)

**Comment by Thomaszzs** [comment]
Kan hende at tables er en grei måte å representere wordgrid på
[Lenke til libgdx sin dokumentasjon på table](https://libgdx.com/wiki/graphics/2d/scene2d/table)
Ifølge chatgpt skal styling også være ganske fleksibelt og du kan style det ved å bruke et [skin objekt](https://libgdx.com/wiki/graphics/2d/scene2d/skin).

**Comment by karenvi** [comment]
Føler at denne må kanskje samarbeide med keyboard? Siden den også vil trenge et grid

**Comment by marcusbirkeland** [comment]
> Føler at denne må kanskje samarbeide med keyboard? Siden den også vil trenge et grid

jepp, men kan i utganspunktet bli utviklet uavhengig av input-system. Kan testes med hardkodet input f.eks.

**Comment by karenvi** [comment]
> > Føler at denne må kanskje samarbeide med keyboard? Siden den også vil trenge et grid
> 
> jepp, men kan i utganspunktet bli utviklet uavhengig av input-system. Kan testes med hardkodet input f.eks.

Ja, er enig, men tenkte mer på at vi trenger vel letter grid for tastaturet? Eller skal vi bare holde det enkelt og la brukeren bruke tastaturet som er på mobilen deres?

Ref bilde av eksempel av hva jeg mener:

Egen wordgrid tastatur:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/61544795/225708437-e4ba491b-6cac-4788-9af7-64503c148069.png">

Eller la brukeren bruke "sitt eget" tastatur:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/61544795/225708743-736c20f4-56bf-4730-b638-85255dc07a4e.png">

Jeg tror kanskje det er enklest å implementere en løsning som lar brukeren få bruke eget tastatur

**Comment by marcusbirkeland** [comment]
Probelmet med mobiltastatur er at da kan vi ikke ha funksjonalitet for deaktivere hvilke bokstaver som er gjettet og ikke er i ordet:

![image](https://user-images.githubusercontent.com/36818485/226502368-b1b03ce8-c35f-48e5-9e0f-60fda1298c92.png)
